version: "3.7"

services:
    flask:
        build: ./flask
        container_name: flask
        restart: always
        environment:
            - APP_NAME=OCRSERVER
        expose:
            - "5000"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 128M
        image: gayeongpark/midubang_flask
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 128M
        image: gayeongpark/midubang_nginx

