version: '3.7'

services:
  nginx:
    # build: ./nginx
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: midubang-nginx
    deploy:
        resources:
            limits:
                cpus: '0.50'
                memory: 512M
            reservations:
                cpus: '0.25'
                memory: 128M
    image: gayeongpark/midubang_nginx
    depends_on:
    #   - web
      - flask
#   web:
#     image: frontend-web:latest
#     ports:
#       - 3000:3000
#     container_name: myweb-web
  flask:
    build: ./flask
    # image: backend-api:latest
    # ports:
    #   - 5000:5000
    expose: 
        - "5000"
    deploy:
        resources:
            limits:
                cpus: '0.50'
                memory: 512M
            reservations:
                cpus: '0.25'
                memory: 128M
    image: gayeongpark/midubang_flask    
    container_name: midubang-flask



# services:
#     flask:
#         build: ./flask
#         container_name: flask
#         restart: always
#         environment:
#             - APP_NAME=OCRSERVER
#         expose:
#             - 5000

#     nginx:
#         build: ./nginx
#         container_name: nginx
#         restart: always
#         ports:
#             - "80:80"


